#!/bin/sh
xrandr --output HDMI2 --auto --right-of eDP1 --output eDP1 --off
# Reapply key mappings because I assume I'll be using my mech when I plug into a monitor
xmodmap ~/.Xmodmap
feh --bg-scale ~/Pictures/aesthetic.jpg
